services:
  accounts-service:
    image: kongcx/accounts-service:latest
    container_name: accounts
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
